name: HeadStart
favicon: null
layout_spectrum: 0
typography_spectrum: 0.31495086569339037
title: 'Brain Training '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070200'
    - '#fac503'
    - '#413182'
    - '#c6792a'
    - '#add7de'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
